### ISSUE TITLE
No Releases (yet)

### ISSUE THREAD

**Issue by ctrezevant** [C0deH4cker/SuperCalc#15]
Hey, 

I'm working on a Homebrew formula for SuperCalc, but Brew formulas require that there be at least one release. If you could [create a new one](https://github.com/C0deH4cker/SuperCalc/releases/new) for SuperCalc, I'd be able to finish that up!

**Comment by chtzvt** [comment]
This is actually not true- the tap proposed in #16 builds the project from source. Closing this.
